### ISSUE TITLE
Consider adding support for TCP_DEFER_ACCEPT and SO_ACCEPTFILTER

### ISSUE THREAD

**Issue by kaniini** [ircd-hybrid/ircd-hybrid#4]
TCP_DEFER_ACCEPT and SO_ACCEPTFILTER are both useful tools to ensure IRCd survives synflood DDoS.

Enabling support for them is straightforward, see https://github.com/atheme/charybdis/blob/master/libratbox/src/commio.c#L772-L788 for an example implementation.

Other implementations I am aware of include InspIRCd, UnrealIRCd 4, and upcoming ratbox 3.1.

**Comment by kaniini** [comment]
As an aside, TLS ports should always have this enabled unconditionally, since clients are required to send ClientHello first.  The only real reason to disable it is to give assistance to BOPM/HOPM.

**Comment by ghost** [comment]
This is strange, 5 year old issues, and confirmed both inspircd and unreal:

https://github.com/inspircd/inspircd/search?q=TCP_DEFER_ACCEPT&unscoped_q=TCP_DEFER_ACCEPT

https://github.com/unrealircd/unrealircd/search?q=TCP_DEFER_ACCEPT&unscoped_q=TCP_DEFER_ACCEPT

 but not and most notably ratbox and right now EFnet is suffering from DDoS `(351:  | [0] mib_a0c5c, [1] ircd-ratbox-3.0.10(20160119_0-29329)., [2] irc.efnet.nl, [3] egGHIKMpZ6 TS6ow 1RC ) ` I haven't been able to find any setsockopt in that code either: 
```
toor@linux-zoxo:~/ircd-ratbox-3.0.10> grep -r TCP_DEFER_ACCEPT
```
I don't know what kind of DDoS mitigation they have but I can't really find out either because nobody is talking about it. I'm not sure if they're using RTBH or if they've hit the limit in terms of what they can jam into a BGP session, or if they're buying DDoS mitigation by throughput (don't know) but I would imagine in any case, this might help just based on reading? 

```
How does the TCP_DEFER_ACCEPT process alter this behaviour?

If the server sets this option on the listener socket then the server will not complete the initial handshake when it receives the empty ACK packet that is intended to complete the connection. Instead the server will discard this packet and will await the following data+ACK packet. When it received this data+ACK packet it will awaken the listener process with a new connection request, and the data is already available for the server process to read.

from: https://www.potaroo.net/ispcol/2011-12/linux-defer-blog.html

The server will only wait a certain time for this data+ACK packet, where the time is set (indirectly) by the server as a parameter to the TCP_DEFER_ACCEPT option. If the timer expires before receiving the data+ACK packet the server will lift its ACK filter and resend the SYN+ACK packet. It will now complete the connection process when it receives an ACK with or without a data payload, at which point it will awaken the listener process to start the session.
```

It would be nice if it were this simple, I'd be interested to hear what you have to say about it now 5 years later, obviously wasn't too irrelevant since they left it open but something needs to get done. As far as the amplification attacks that go on (observed a few from these idiots) they should be dumping packet logs and billing the origin host companies for the inconvenience, but this issue should definitely be considered and/or closed.

**Comment by synandro** [comment]
EFnet's issues are unrelated to any ircd issues.  DDoS is still a thing.

TCP_DEFER_ACCEPT is inappropriate for use with the irc protocol. Here is why, if the client never sends any data to the server, the server never sends the on connect notices to the ircd.  If you have a client that waits for the NOTICE...nothing proceeds further.  
Also TCP_DEFER_ACCEPT delays processing of things like D/Klines since you are waiting for the client to send data still.

TCP_DEFER_ACCEPT is designed for HTTP servers, mostly.

**Comment by synandro** [comment]
EFnet's issues are unrelated to any ircd issues.  DDoS is still a thing.

TCP_DEFER_ACCEPT is inappropriate for use with the irc protocol. Here is why, if the client never sends any data to the server, the server never sends the on connect notices to the ircd.  If you have a client that waits for the NOTICE...nothing proceeds further.  
Also TCP_DEFER_ACCEPT delays processing of things like D/Klines since you are waiting for the client to send data still.

TCP_DEFER_ACCEPT is designed for HTTP servers, mostly.  This is why ircd-ratbox does not use it :)

**Comment by kaniini** [comment]
As I said 5 years ago, "the only real reason to disable it is to give assistance to BOPM/HOPM."

`TCP_DEFER_ACCEPT` does delay processing of k-lines, but does not starve the IRCd of file descriptors, so it does not matter.

**Comment by miwob** [comment]
I see no harm implementing this as it can be totally optional.
